### ISSUE TITLE
Task: Testing the product

### ISSUE THREAD

**Issue by IsabelleCzuboka** [amczuboka/Decagon-CondoManagementSystem#92]
Set up a scanning tool like SonarQube to determine what percentage of the code is covered.

**Comment by IsabelleCzuboka** [comment]
#7

**Comment by Guillaume-Lachapelle** [comment]
UPDATE: We decided to use "npm run test-headless" which runs the command "ng test --no-watch --no-progress --browsers=ChromeHeadless --code-coverage". This allows us to get the code coverage for the unit tests, and we check if that value is over 80%.
This is done automatically upon every push and every PR on the repository since it is integrated into the CD/CI pipeline. The pipeline build will fail if that coverage condition is not met or if any test fails, including the cypress tests.
